services:
  nginx-service1:
    extends:
      file: base/common-service.yml
      service: nginx-service
    container_name: first-container-name
    volumes:
      - ./nginx/html/index.html:/usr/share/nginx/html/index.html
    networks:
      - nginx-network

  nginx-service2:
    extends:
      file: base/common-service.yml
      service: nginx-service
    container_name: second-container-name
    volumes:
      - ./nginx/html/index2.html:/usr/share/nginx/html/index.html
    networks:
      - nginx-network

  nginx-service3:
    extends:
      file: base/common-service.yml
      service: nginx-service
    container_name: third-container-name
    volumes:
      - ./nginx/html/index3.html:/usr/share/nginx/html/index.html
    networks:
      - nginx-network

  load-balancer:
    extends:
      file: base/common-service.yml
      service: nginx-service
    container_name: load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-network

networks:
  nginx-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1