services:
  nginx-service:
    image: nginx:alpine
    container_name: nginx-container

networks:
  nginx-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1